/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntofuncion;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabir
 */
public class VentanaTablaPFNA extends javax.swing.JFrame {
    DefaultTableModel modeloTPFNA = new DefaultTableModel();
    private final ManejaElementoFuncional me;
    private int resultado;
    /**
     * Creates new form VentanaTablaPFNA
     */
    public VentanaTablaPFNA(ManejaElementoFuncional m) {
        initComponents();
        me = m;
        this.dibujarTabla();
        this.llenarTabla();
    }
    
    public void dibujarTabla(){
        this.jTablePFNA.setModel(modeloTPFNA);
        String[]columnasTablaPFNA = {"Descripción", "Sencilla", "Media", "Compleja", "TOTAL P.F."};
        modeloTPFNA.setColumnIdentifiers(columnasTablaPFNA);
        
        jTablePFNA.getColumnModel().getColumn(0).setPreferredWidth(65);
        jTablePFNA.getColumnModel().getColumn(1).setPreferredWidth(25);
        jTablePFNA.getColumnModel().getColumn(2).setPreferredWidth(25);
        jTablePFNA.getColumnModel().getColumn(3).setPreferredWidth(25);
        jTablePFNA.getColumnModel().getColumn(4).setPreferredWidth(25);
        
        jTablePFNA.getTableHeader().setResizingAllowed(false);
    }
    
    public void llenarTabla(){
        //int EEs = 0, EEm = 0, EEc = 0, SEs = 0, SEm = 0, SEc = 0, FLIs = 0, FLIm = 0, FLIc = 0, FLEs = 0, FLEm = 0, FLEc = 0, CEs = 0, CEm = 0, CEc = 0, TEE = 0, TSE = 0, TFLI = 0, TFLE = 0, TCE = 0, T = 0;
        int[]tmp = new int[21];
        tmp = me.getPFNA();
        jTablePFNA.setModel(modeloTPFNA);
        modeloTPFNA.addRow(new Object[]{"EE", tmp[0] + " x 3", tmp[1] + " x 4", tmp[2] + " x 6", tmp[3]});
        modeloTPFNA.addRow(new Object[]{"SE", tmp[4] + " x 4", tmp[5] + " x 5", tmp[6] + " x 7", tmp[7]});
        modeloTPFNA.addRow(new Object[]{"FLI", tmp[8] + " x 7", tmp[9] + " x 10", tmp[10] + " x 15", tmp[11]});
        modeloTPFNA.addRow(new Object[]{"FLE", tmp[12] + " x 5", tmp[13] + " x 7", tmp[14] + " x 10", tmp[15]});
        modeloTPFNA.addRow(new Object[]{"CE", tmp[16] + " x 3", tmp[17] + " x 4", tmp[18] + " x 6", tmp[19]});
        modeloTPFNA.addRow(new Object[]{"TOTAL", null, null, null, tmp[20]});
        this.resultado = tmp[20];
    }
    
    public int getResultado(){
        return resultado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePFNA = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablePFNA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePFNA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(535, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(VentanaTablaPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(VentanaTablaPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(VentanaTablaPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(VentanaTablaPFNA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new VentanaTablaPFNA().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePFNA;
    // End of variables declaration//GEN-END:variables
}
